# Generated by Django 4.2.11 on 2024-04-23 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecryptKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decrypt_key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EncryptedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SecureTextURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('decrypte_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securetext.decryptkey')),
                ('encrypted_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securetext.encryptedmessage')),
            ],
        ),
    ]
